// <auto-generated />
using System;
using AppExamen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppExamen.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20201012215350_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppExamen.Models.tbl_usuario", b =>
                {
                    b.Property<int>("usu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cod_rol")
                        .HasColumnType("int");

                    b.Property<DateTime>("fec_ins")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fec_upd")
                        .HasColumnType("datetime2");

                    b.Property<string>("usu_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usu_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("usu_estado")
                        .HasColumnType("int");

                    b.Property<string>("usu_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usu_id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
